version: '2.4'
services:
  phoxi_docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: phoxi_docker
    network_mode: "host"
    runtime: "nvidia"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - /dev/shm:/dev/shm
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    privileged: true
    stdin_open: true
    tty: true
    security_opt:
      - apparmor=unconfined


